<div class="footer-content-category">
    <?php
    echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer_content_category_title')
        ->toHtml();
    echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer_content_category_content')
        ->toHtml();
    ?>
</div>
<div class="footer-content-shop-info">
    <?php
    echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer_content_shop_info_title')
        ->toHtml();
    echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer_content_shop_info_content')
        ->toHtml();
    ?>
</div>
<div class="footer-content-policy">
    <?php
    echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('ooter_content_policy_title')
        ->toHtml();
    echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('footer_content_policy_content')
        ->toHtml();
    ?>
</div>
<div id="footer-content-accordion" data-mage-init='{
        "accordion":{
            "active": false,
            "collapsible": true
        }}'>
    <div data-role="collapsible">
        <div data-role="trigger">
            <?php echo $block->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('footer_content_category_title')
                ->toHtml();
            ?>
        </div>
    </div>
    <div data-role="content">
        <?php echo $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('footer_content_category_content')
            ->toHtml();
        ?>
    </div>

    <div data-role="collapsible">
        <div data-role="trigger">
            <?php echo $block->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('footer_content_shop_info_title')
                ->toHtml();
            ?>
        </div>
    </div>
    <div data-role="content">
        <?php echo $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('footer_content_shop_info_content')
            ->toHtml();
        ?>
    </div>

    <div data-role="collapsible">
        <div data-role="trigger">
            <?php echo $block->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('footer_content_policy_title')
                ->toHtml();
            ?>
        </div>
    </div>
    <div data-role="content">
        <?php echo $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('footer_content_policy_content')
            ->toHtml();
        ?>
    </div>
</div>