<div class="header-top-desktop-left">
    Contact us / <a href="tel:+<?= $block->getLayout()
                                    ->createBlock('Magento\Cms\Block\Block')
                                    ->setBlockId('header_contact_us')
                                    ->toHtml() ?>">
        <?= $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('header_contact_us')
            ->toHtml();
        ?>
    </a>
</div>