<div class="header-top-desktop-left">
    Contact us / <a href="tel:+">
        <?= $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('header_contact_us')
            ->toHtml();
        ?>
    </a>
</div>

<div class="header-top-desktop-center">
    <ul>
        <?php
        echo $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('header_top_list_link')
            ->toHtml();
        ?>
    </ul>
</div>

<div class="header-top-social">
    <?php
    echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('header_top_social')
        ->toHtml();
    ?>
</div>

<div class="header-top-blog">
    <a href="#">Blog</a>
</div>