<div class="header-top-mobile-left">
    <?php echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('header_top_store_list_mobile')
        ->toHtml();
    ?>
</div>

<div class="header-top-desktop-left header-top-mobile-right">
    <?php echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('header_top_left')
        ->toHtml();
    ?>
</div>

<div class="header-top-desktop-center">
    <ul>
        <?php echo $block->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('header_top_store_list_desktop')
            ->toHtml();
        ?>
    </ul>
</div>

<div class="header-top-social">
    <?php echo $block->getLayout()
        ->createBlock('Magento\Cms\Block\Block')
        ->setBlockId('header_top_social')
        ->toHtml();
    ?>
</div>

<div class="header-top-blog">
    <a href="#">Blog</a>
</div>